version: '3.8'

services:
  mongo:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 10s
      timeout: 30s
      start_period: 0s
      retries: 30
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"

  anonymous-buyers:
    container_name: anonymous-buyers
    build:
      context: anonymous-buyers
      dockerfile: Dockerfile
    hostname: anonymous-buyers
    volumes:
      - ./anonymous-buyers:/anonymous-buyers
    ports:
      - 4000:4000
    environment:
      - DB_URI=${DB_URI}

volumes:
  mongo1_data:
  mongo1_config:
